
export const SET_FOOD_LIST_PENDING = 'SET_FOOD_LIST_PENDING';
export const SET_FOOD_LIST_FULFILLED = 'SET_FOOD_LIST_FULFILLED';
export const SET_FOOD_LIST_REJECTED = 'SET_FOOD_LIST_REJECTED';

export const SAVE_FOOD_LIST = 'SAVE_FOOD_LIST';

export const DELETE_FOOD_ITEM_PENDING = 'DELETE_FOOD_ITEM_PENDING';
export const DELETE_FOOD_ITEM_FULFILLED = 'DELETE_FOOD_ITEM_FULFILLED';
export const DELETE_FOOD_ITEM_REJECTED = 'DELETE_FOOD_ITEM_REJECTED';

export const ADD_FOOD_ITEM_PENDING = 'ADD_FOOD_ITEM_PENDING';
export const ADD_FOOD_ITEM_FULFILLED = 'ADD_FOOD_ITEM_FULFILLED';
export const ADD_FOOD_ITEM_REJECTED = 'ADD_FOOD_ITEM_REJECTED';

export const EDIT_FOOD_ITEM = 'EDIT_FOOD_ITEM';
